### ISSUE TITLE
タイトルかっこいいフォントで

### ISSUE THREAD

**Issue by WK005** [masa0228/iniad-fake-homepage#11]
タイトルのフォントをかっこいいやつに変更。
テキストを英字に変更。「INIAD OPEN CAMPUS」
フォントサイズも大きくして目立たせる。

**Comment by WK005** [comment]
タイトルを英字にしました。
フォントを変更しました。
画像の上に配置しました。

**Comment by INIAD22004kt** [comment]
フォントが変わってサイトの印象がかっこよくなりましたね。
