### ISSUE TITLE
目次を作る

### ISSUE THREAD

**Issue by moeiwata** [masa0228/iniad-fake-homepage#13]
最初にどんな項目が載っているのか見せる

**Comment by INIAD22004kt** [comment]
岩田様、目次はどのような内容をお考えでしょうか。
INIADサイトの左側一覧のようなものでならば、コンテンツを左右に分割してPC版は左側に表示、スマホ版は画面の上60pxに固定などができると思います。Moocsのsample3.htmlのようなイメージです。
いかがでしょうか。

**Comment by moeiwata** [comment]
ありがとうございます。Moocsのサンプルがどれだかわからないのですが、単純にページ上部にインデックスを記載するイメージでした。

**Comment by INIAD22004kt** [comment]
スクリーンショットのようなイメージです。
Moocsの章としては、web3:フロントエンド:CSS　7の3ページ目と4ページ目あたりです。
目次はどのような内容を記載する予定でしょうか？
![Screenshot 2022-11-30 20 59 08](https://user-images.githubusercontent.com/118710199/204790772-6540c1a4-4054-453a-be7c-583ab428e482.png)

**Comment by moeiwata** [comment]
共有ありがとうございます。目次は概要・スケジュール・つぶやき・INIADとは？を記載する想定でした。

**Comment by INIAD22004kt** [comment]
目次の予定を教えていただきありがとうございます。
良い感じにできるといいですね。

**Comment by moeiwata** [comment]
目次追加してみました！いろいろとご教示いただきありがとうございました。

**Comment by INIAD22004kt** [comment]
目次作成ありがとうございました！slack等に書き込みましたが、スマホ対応があまり上手く表現できませんでした。今回は諦めることにします。申し訳ありません。
